'use client'
import { useEffect, useState } from 'react'
import type { Product } from '@/lib/types'
import { money } from '@/lib/data'

export function ProductModal({ product, onClose, onAdd }: { product: Product; onClose: () => void; onAdd: () => void }) {
  const photos = [product.imageUrl, ...(product.gallery ?? [])].filter(Boolean) as string[]
  const [active, setActive] = useState(0)
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; document.addEventListener('keydown', onKeyDown); document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', onKeyDown); document.body.style.overflow = '' } }, [onClose])
  return <div className="product-modal-backdrop" role="presentation" onClick={onClose}><section className="product-modal" role="dialog" aria-modal="true" aria-label={product.name} onClick={event => event.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close product details">×</button><div className="modal-gallery"><div className={`modal-main-photo product-art ${product.color}`}>{photos[active] ? <img src={photos[active]} alt={product.name} /> : <span className="product-emoji">{product.emoji}</span>}</div><div className="modal-thumbnails">{photos.map((photo, index) => <button className={index === active ? 'active' : ''} key={photo} onClick={() => setActive(index)}><img src={photo} alt={`${product.name} view ${index + 1}`} /></button>)}</div></div><div className="modal-content"><p className="eyebrow">{product.category.toUpperCase()}</p><h2>{product.name}</h2><div className="rating">★ {product.rating} <small>{product.reviews.toLocaleString('en-IN')} ratings</small></div><p className="modal-price">{money(product.price)} <del>{money(product.oldPrice)}</del></p><p className="modal-description">{product.description ?? 'A carefully selected product for everyday use.'}</p><div className="modal-detail-grid">{product.details?.packSize && <div><small>Pack size</small><strong>{product.details.packSize}</strong></div>}{product.details?.material && <div><small>Material</small><strong>{product.details.material}</strong></div>}{product.details?.warranty && <div><small>Warranty</small><strong>{product.details.warranty}</strong></div>}{product.details?.expiry && <div><small>Expiry</small><strong>{product.details.expiry}</strong></div>}{product.details?.origin && <div><small>Origin</small><strong>{product.details.origin}</strong></div>}</div>{product.details?.highlights?.length ? <div className="modal-highlights"><h3>What you get</h3><ul>{product.details.highlights.map(item => <li key={item}>{item}</li>)}</ul></div> : null}<button className="primary-button modal-add" disabled={!product.stock} onClick={onAdd}>{product.stock ? 'Add to cart' : 'Out of stock'}</button></div></section></div>
}
