'use client'

import Image from 'next/image'
import { placements } from '@/constants/admin-banners'
import type { BannerForm } from '@/types/admin-banner'

export function BannerEditor({ form, editing, poster, posterPreview, error, message, saving, updateForm, choosePoster, replacePoster, resetForm, save }: { form: BannerForm; editing: number | null; poster: File | null; posterPreview: string; error: string; message: string; saving: boolean; updateForm: <K extends keyof BannerForm>(key: K, value: BannerForm[K]) => void; choosePoster: (event: React.ChangeEvent<HTMLInputElement>) => void; replacePoster: () => void; resetForm: () => void; save: () => void }) {
  return <section className="panel banner-editor"><div className="banner-editor-heading"><div><p className="eyebrow">POSTER EDITOR</p><h2>{editing ? 'Edit poster' : 'Add a poster'}</h2><p>Upload the finished artwork, then add optional text that appears over it.</p></div>{editing && <button className="secondary-button" onClick={resetForm}>New poster</button>}</div><label className={`poster-dropzone ${posterPreview ? 'has-poster' : ''}`}>{posterPreview ? <Image src={posterPreview} alt="Poster preview" fill unoptimized sizes="(max-width: 900px) 100vw, 620px" /> : <><span className="poster-upload-icon">＋</span><strong>Drop a poster here or browse</strong><small>Use a wide JPG, PNG or WebP image</small></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={choosePoster} /></label><div className="poster-upload-actions">{posterPreview && <button type="button" className="secondary-button" onClick={replacePoster}>Replace poster</button>}<small>Recommended: 1400 × 500 px or wider</small></div><div className="banner-settings"><div className="banner-settings-heading"><div><h3>Placement &amp; message</h3><p>Keep the artwork clean; use these fields only when text is needed.</p></div><label className="banner-active"><input type="checkbox" checked={form.active} onChange={event => updateForm('active', event.target.checked)} /> Publish now</label></div><div className="form-grid"><label>Show on<select value={form.placement} onChange={event => updateForm('placement', event.target.value)}>{placements.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Display order<input type="number" min="0" value={form.sortOrder} onChange={event => updateForm('sortOrder', event.target.value)} /></label><label>Headline<input value={form.title} onChange={event => updateForm('title', event.target.value)} placeholder="Summer essentials, delivered" /></label><label>Supporting text<textarea value={form.copy} onChange={event => updateForm('copy', event.target.value)} placeholder="Optional text shown on the poster." /></label></div></div><div className="banner-form-footer"><div>{error && <p className="low-stock">{error}</p>}{message && <p className="success-message">{message}</p>}</div><button className="primary-button" onClick={() => void save()} disabled={saving || (!poster && !form.imageUrl)}>{saving ? 'Publishing…' : editing ? 'Save changes' : 'Publish poster'}</button></div></section>
}
