-- Phase 4 completion: notifications, delivery proof, dashboard metrics and product media.
-- Run after schema.sql, phase3_admin.sql and the other phase4 scripts.

alter table public.orders add column if not exists assigned_to uuid references public.users(id);
alter table public.orders add column if not exists delivery_notes text;
alter table public.orders add column if not exists proof_of_delivery_url text;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  order_id bigint references public.orders(id) on delete cascade,
  title text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.notifications add column if not exists message text;
alter table public.notifications add column if not exists body text;
alter table public.notifications add column if not exists created_at timestamptz not null default now();
alter table public.notifications add column if not exists order_id bigint references public.orders(id) on delete cascade;
update public.notifications set message = coalesce(message, body, title) where message is null;

alter table public.notifications enable row level security;
drop policy if exists "users read own notifications" on public.notifications;
create policy "users read own notifications" on public.notifications for select using (user_id = auth.uid());
drop policy if exists "users update own notifications" on public.notifications;
create policy "users update own notifications" on public.notifications for update using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.notify_order_status_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.status is distinct from old.status and new.user_id is not null then
    insert into public.notifications(user_id, order_id, title, message)
    values (new.user_id, new.id, 'Order status updated', 'Order #' || new.id || ' is now ' || replace(new.status::text, '_', ' ') || '.');
  end if;
  return new;
end;
$$;

drop trigger if exists order_status_notification on public.orders;
create trigger order_status_notification
after update of status on public.orders
for each row execute function public.notify_order_status_change();

create or replace function public.customer_list_notifications()
returns table(notification_id bigint, order_id bigint, title text, message text, read_at timestamptz, created_at timestamptz)
language sql security invoker set search_path = public as $$
  select n.id, n.order_id, n.title, n.message, n.read_at, n.created_at
  from public.notifications n
  where n.user_id = auth.uid()
  order by n.created_at desc
  limit 30;
$$;

create or replace function public.customer_mark_notification_read(p_notification_id bigint)
returns void language sql security invoker set search_path = public as $$
  update public.notifications set read_at = coalesce(read_at, now())
  where id = p_notification_id and user_id = auth.uid();
$$;

grant execute on function public.customer_list_notifications() to authenticated;
grant execute on function public.customer_mark_notification_read(bigint) to authenticated;

create or replace function public.admin_update_delivery_details(
  p_order_id bigint,
  p_status public.order_status default null,
  p_assigned_to uuid default null,
  p_delivery_notes text default null,
  p_proof_of_delivery_url text default null
)
returns void language plpgsql security invoker set search_path = public as $$
begin
  if not (public.has_role('delivery_boy') or public.has_role('picker') or public.has_role('store_manager') or public.has_role('super_admin')) then
    raise exception 'ADMIN_REQUIRED';
  end if;
  update public.orders
  set status = coalesce(p_status, status),
      assigned_to = coalesce(p_assigned_to, assigned_to),
      delivery_notes = coalesce(p_delivery_notes, delivery_notes),
      proof_of_delivery_url = coalesce(p_proof_of_delivery_url, proof_of_delivery_url)
  where id = p_order_id;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
end;
$$;

grant execute on function public.admin_update_delivery_details(bigint,public.order_status,uuid,text,text) to authenticated;

create or replace view public.dashboard_top_products as
select p.id as product_id, p.name as product_name,
       coalesce(sum(oi.quantity) filter (where o.status <> 'cancelled'), 0)::integer as units_sold,
       coalesce(sum(oi.quantity * oi.unit_price) filter (where o.status <> 'cancelled'), 0)::numeric as revenue
from public.products p
left join public.order_items oi on oi.product_id = p.id
left join public.orders o on o.id = oi.order_id
group by p.id, p.name
order by units_sold desc, p.name;

create or replace view public.dashboard_low_stock as
select i.product_id, p.name as product_name, i.current_stock, i.reserved_stock, i.reorder_level
from public.inventory i join public.products p on p.id = i.product_id
where i.current_stock <= i.reorder_level
order by i.current_stock, p.name;

alter view public.dashboard_top_products set (security_invoker = true);
alter view public.dashboard_low_stock set (security_invoker = true);

create or replace function public.admin_add_product_image(
  p_product_id bigint,
  p_storage_path text,
  p_alt_text text default null,
  p_sort_order integer default 0
)
returns bigint language plpgsql security invoker set search_path = public as $$
declare v_id bigint;
begin
  if not public.has_role('super_admin') and not public.has_role('store_manager') then raise exception 'ADMIN_REQUIRED'; end if;
  insert into public.product_images(product_id, storage_path, alt_text, sort_order)
  values (p_product_id, p_storage_path, p_alt_text, p_sort_order)
  returning id into v_id;
  return v_id;
end;
$$;

grant execute on function public.admin_add_product_image(bigint,text,text,integer) to authenticated;

-- Product media bucket. The client still uses signed/authenticated uploads.
insert into storage.buckets(id, name, public)
values ('product-media', 'product-media', true)
on conflict (id) do nothing;

drop policy if exists "admins upload product media" on storage.objects;
create policy "admins upload product media" on storage.objects
for insert to authenticated
with check (bucket_id = 'product-media' and (public.has_role('super_admin') or public.has_role('store_manager')));

drop policy if exists "public read product media" on storage.objects;
create policy "public read product media" on storage.objects
for select using (bucket_id = 'product-media');
