-- Phase 3: catalogue, coupons, support and purchasing administration.

alter table public.products add column if not exists is_active boolean not null default true;

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  order_id bigint references public.orders(id),
  subject text not null,
  message text not null,
  priority text not null default 'medium',
  status text not null default 'open',
  created_at timestamptz not null default now()
);
alter table public.support_tickets enable row level security;

create or replace function public.admin_list_products()
returns table (product_id bigint, product_name text, sku text, category_name text, brand_name text, selling_price numeric, current_stock integer, is_active boolean)
language plpgsql security definer set search_path = public
as $$
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  return query select p.id::bigint, p.name::text, p.sku::text, c.name::text, b.name::text,
    p.selling_price::numeric, coalesce(i.current_stock, 0)::integer, p.is_active
  from public.products p
  left join public.categories c on c.id = p.category_id
  left join public.brands b on b.id = p.brand_id
  left join public.inventory i on i.product_id = p.id
  order by p.name;
end;
$$;

create or replace function public.admin_upsert_product(
  p_product_id bigint default null,
  p_name text default '', p_sku text default null, p_barcode text default null,
  p_brand text default null, p_category text default null, p_description text default null,
  p_selling_price numeric default 0, p_mrp numeric default 0, p_gst numeric default 0,
  p_hsn text default null, p_stock integer default 0
)
returns bigint
language plpgsql security definer set search_path = public
as $$
declare v_id bigint; v_category bigint; v_brand bigint; v_slug text;
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  if nullif(trim(p_name), '') is null or p_selling_price < 0 then raise exception 'INVALID_PRODUCT'; end if;
  if nullif(trim(p_category), '') is not null then
    insert into public.categories(name, slug) values (trim(p_category), regexp_replace(lower(trim(p_category)), '[^a-z0-9]+', '-', 'g'))
    on conflict (slug) do update set name = excluded.name returning id into v_category;
  end if;
  if nullif(trim(p_brand), '') is not null then
    insert into public.brands(name, slug) values (trim(p_brand), regexp_replace(lower(trim(p_brand)), '[^a-z0-9]+', '-', 'g'))
    on conflict (slug) do update set name = excluded.name returning id into v_brand;
  end if;
  if p_product_id is null then
    v_slug := regexp_replace(lower(trim(p_name)), '[^a-z0-9]+', '-', 'g');
    insert into public.products(name, slug, sku, barcode, brand_id, category_id, description, selling_price, mrp, gst, hsn)
    values (trim(p_name), v_slug || '-' || extract(epoch from now())::bigint, nullif(trim(p_sku), ''), nullif(trim(p_barcode), ''), v_brand, v_category, p_description, p_selling_price, greatest(p_mrp, p_selling_price), p_gst, p_hsn)
    returning id into v_id;
    insert into public.inventory(product_id, current_stock, warehouse_stock) values (v_id, greatest(p_stock, 0), greatest(p_stock, 0));
  else
    update public.products set name = trim(p_name), sku = nullif(trim(p_sku), ''), barcode = nullif(trim(p_barcode), ''), brand_id = v_brand, category_id = v_category, description = p_description, selling_price = p_selling_price, mrp = greatest(p_mrp, p_selling_price), gst = p_gst, hsn = p_hsn where id = p_product_id returning id into v_id;
    if v_id is null then raise exception 'PRODUCT_NOT_FOUND'; end if;
    update public.inventory set current_stock = greatest(p_stock, reserved_stock), warehouse_stock = greatest(p_stock, reserved_stock) where product_id = v_id;
  end if;
  return v_id;
end;
$$;

create or replace function public.admin_toggle_product(p_product_id bigint, p_active boolean)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  update public.products set is_active = p_active where id = p_product_id;
  if not found then raise exception 'PRODUCT_NOT_FOUND'; end if;
  return p_active;
end; $$;

create or replace function public.admin_list_coupons()
returns table (coupon_id bigint, code text, kind text, value numeric, starts_at timestamptz, ends_at timestamptz, active boolean)
language plpgsql security definer set search_path = public as $$
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  return query select c.id::bigint, c.code::text, c.kind::text, c.value::numeric, c.starts_at, c.ends_at, c.active from public.coupons c order by c.id desc;
end; $$;

create or replace function public.admin_upsert_coupon(p_coupon_id bigint default null, p_code text default '', p_kind text default 'percentage', p_value numeric default 0, p_starts_at timestamptz default null, p_ends_at timestamptz default null, p_active boolean default true)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  if nullif(trim(p_code), '') is null or p_value < 0 then raise exception 'INVALID_COUPON'; end if;
  if p_coupon_id is null then insert into public.coupons(code, kind, value, starts_at, ends_at, active) values (upper(trim(p_code)), p_kind, p_value, p_starts_at, p_ends_at, p_active) returning id into v_id;
  else update public.coupons set code = upper(trim(p_code)), kind = p_kind, value = p_value, starts_at = p_starts_at, ends_at = p_ends_at, active = p_active where id = p_coupon_id returning id into v_id; end if;
  if v_id is null then raise exception 'COUPON_NOT_FOUND'; end if; return v_id;
end; $$;

create or replace function public.admin_delete_coupon(p_coupon_id bigint)
returns bigint language plpgsql security definer set search_path = public as $$
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  delete from public.coupons where id = p_coupon_id;
  if not found then raise exception 'COUPON_NOT_FOUND'; end if;
  return p_coupon_id;
end; $$;

create or replace function public.admin_list_support_tickets()
returns table (ticket_id bigint, customer_name text, subject text, message text, priority text, status text, created_at timestamptz)
language plpgsql security definer set search_path = public as $$
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  return query select t.id, coalesce(nullif(u.full_name, ''), 'Customer'), t.subject, t.message, t.priority, t.status, t.created_at
  from public.support_tickets t left join public.users u on u.id = t.user_id order by t.created_at desc;
end; $$;

create or replace function public.admin_update_ticket_status(p_ticket_id bigint, p_status text)
returns text language plpgsql security definer set search_path = public as $$
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  update public.support_tickets set status = p_status where id = p_ticket_id;
  if not found then raise exception 'TICKET_NOT_FOUND'; end if; return p_status;
end; $$;

create or replace function public.admin_list_purchase_orders()
returns table (purchase_order_id bigint, supplier_name text, status text, created_at timestamptz, item_count bigint)
language plpgsql security definer set search_path = public as $$
begin
  if not public.has_role('inventory_manager') and not public.has_role('store_manager') then raise exception 'PURCHASE_ROLE_REQUIRED'; end if;
  return query select po.id, coalesce(s.name, 'Unassigned supplier'), po.status, po.created_at, count(pi.id)::bigint
  from public.purchase_orders po left join public.suppliers s on s.id = po.supplier_id left join public.purchase_items pi on pi.purchase_order_id = po.id
  group by po.id, s.name order by po.created_at desc;
end; $$;

create or replace function public.admin_list_customers()
returns table (customer_id uuid, customer_name text, email text, phone text, order_count bigint, lifetime_spend numeric, joined_at timestamptz)
language plpgsql security definer set search_path = public as $$
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  return query
    select u.id, coalesce(nullif(u.full_name, ''), split_part(coalesce(a.email, ''), '@', 1), 'Customer')::text,
      coalesce(a.email, '')::text, u.phone::text, count(o.id)::bigint,
      coalesce(sum(o.total) filter (where o.status <> 'cancelled'), 0)::numeric, u.created_at
    from public.users u
    join auth.users a on a.id = u.id
    left join public.orders o on o.user_id = u.id
    left join public.roles r on r.id = u.role_id
    where coalesce(r.name::text, 'customer') = 'customer'
    group by u.id, u.full_name, a.email, u.phone, u.created_at
    order by u.created_at desc;
end; $$;

create or replace function public.admin_create_purchase_order(p_supplier_name text, p_product_id bigint, p_quantity integer, p_unit_cost numeric)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_supplier_id bigint; v_order_id bigint;
begin
  if not (public.has_role('inventory_manager') or public.has_role('store_manager')) then raise exception 'PURCHASE_ROLE_REQUIRED'; end if;
  if nullif(trim(p_supplier_name), '') is null or p_quantity < 1 or p_unit_cost < 0 then raise exception 'INVALID_PURCHASE_ORDER'; end if;
  select id into v_supplier_id from public.suppliers where lower(name) = lower(trim(p_supplier_name)) limit 1;
  if v_supplier_id is null then insert into public.suppliers(name) values (trim(p_supplier_name)) returning id into v_supplier_id; end if;
  insert into public.purchase_orders(supplier_id, status) values (v_supplier_id, 'draft') returning id into v_order_id;
  insert into public.purchase_items(purchase_order_id, product_id, quantity, unit_cost) values (v_order_id, p_product_id, p_quantity, p_unit_cost);
  return v_order_id;
end; $$;

grant execute on function public.admin_list_products() to authenticated;
grant execute on function public.admin_upsert_product(bigint,text,text,text,text,text,text,numeric,numeric,numeric,text,integer) to authenticated;
grant execute on function public.admin_toggle_product(bigint,boolean) to authenticated;
grant execute on function public.admin_list_coupons() to authenticated;
grant execute on function public.admin_upsert_coupon(bigint,text,text,numeric,timestamptz,timestamptz,boolean) to authenticated;
grant execute on function public.admin_delete_coupon(bigint) to authenticated;
grant execute on function public.admin_list_support_tickets() to authenticated;
grant execute on function public.admin_update_ticket_status(bigint,text) to authenticated;
grant execute on function public.admin_list_purchase_orders() to authenticated;
grant execute on function public.admin_create_purchase_order(text,bigint,integer,numeric) to authenticated;
grant execute on function public.admin_list_customers() to authenticated;
