-- Phase 4: live promotional banner management.

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  placement text not null default 'homepage',
  title text not null,
  copy text,
  image_url text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.banners enable row level security;
drop policy if exists "active banners are public" on public.banners;
create policy "active banners are public" on public.banners for select using (active = true);

create or replace function public.admin_list_banners()
returns table (banner_id bigint, placement text, title text, copy text, image_url text, active boolean, sort_order integer)
language plpgsql security definer set search_path = public as $$
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  return query select b.id, b.placement, b.title, b.copy, b.image_url, b.active, b.sort_order from public.banners b order by b.placement, b.sort_order, b.id;
end; $$;

create or replace function public.admin_upsert_banner(p_banner_id bigint default null, p_placement text default 'homepage', p_title text default '', p_copy text default null, p_image_url text default '', p_active boolean default true, p_sort_order integer default 0)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  if nullif(trim(p_title), '') is null or nullif(trim(p_image_url), '') is null then raise exception 'BANNER_CONTENT_REQUIRED'; end if;
  if p_banner_id is null then insert into public.banners(placement, title, copy, image_url, active, sort_order) values (lower(trim(p_placement)), trim(p_title), p_copy, trim(p_image_url), p_active, p_sort_order) returning id into v_id;
  else update public.banners set placement = lower(trim(p_placement)), title = trim(p_title), copy = p_copy, image_url = trim(p_image_url), active = p_active, sort_order = p_sort_order where id = p_banner_id returning id into v_id; end if;
  if v_id is null then raise exception 'BANNER_NOT_FOUND'; end if; return v_id;
end; $$;

grant execute on function public.admin_list_banners() to authenticated;
grant execute on function public.admin_upsert_banner(bigint,text,text,text,text,boolean,integer) to authenticated;

