-- Segment 4 payments and order lifecycle hardening.
-- Run after phase4_orders.sql and phase5_payments.sql.

alter table public.orders add column if not exists payment_captured_at timestamptz;
alter table public.orders add column if not exists cancelled_at timestamptz;
alter table public.orders add column if not exists stock_restored_at timestamptz;
alter table public.payments add column if not exists captured_at timestamptz;

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  provider text not null default 'razorpay',
  event_id text not null,
  event_name text not null,
  gateway_order_id text,
  gateway_payment_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(provider, event_id)
);
alter table public.payment_events enable row level security;
revoke all on public.payment_events from anon, authenticated;
grant all on public.payment_events to service_role;
create unique index if not exists payments_gateway_order_unique_idx on public.payments(gateway_order_id) where gateway_order_id is not null;
create unique index if not exists payments_gateway_payment_unique_idx on public.payments(gateway_payment_id) where gateway_payment_id is not null;

alter table public.payments drop constraint if exists payments_method_check;
-- Normalize legacy values before enforcing the stricter payment-method set.
update public.payments
set method = case
  when lower(trim(method)) in ('upi') then 'upi'
  when lower(trim(method)) in ('card', 'credit_card', 'debit_card', 'credit/debit card') then 'card'
  when lower(trim(method)) in ('netbanking', 'net banking') then 'netbanking'
  when lower(trim(method)) in ('wallet') then 'wallet'
  when lower(trim(method)) in ('cod', 'cash on delivery') then 'cod'
  else 'Razorpay'
end
where method is distinct from case
  when lower(trim(method)) in ('upi') then 'upi'
  when lower(trim(method)) in ('card', 'credit_card', 'debit_card', 'credit/debit card') then 'card'
  when lower(trim(method)) in ('netbanking', 'net banking') then 'netbanking'
  when lower(trim(method)) in ('wallet') then 'wallet'
  when lower(trim(method)) in ('cod', 'cash on delivery') then 'cod'
  else 'Razorpay'
end;
alter table public.payments add constraint payments_method_check check (method in ('upi','card','netbanking','wallet','cod','Razorpay'));

create or replace function public.restore_order_stock(p_order_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.orders set stock_restored_at = now() where id = p_order_id and stock_restored_at is null;
  if not found then return; end if;
  update public.inventory i set current_stock = i.current_stock + items.quantity, warehouse_stock = i.warehouse_stock + items.quantity
  from (select product_id, sum(quantity)::integer quantity from public.order_items where order_id = p_order_id group by product_id) items
  where i.product_id = items.product_id;
end;
$$;

create or replace function public.system_mark_payment_failed(p_gateway_order_id text)
returns void language plpgsql security definer set search_path = public as $$
declare v_order_id bigint;
begin
  select order_id into v_order_id from public.payments where gateway_order_id = p_gateway_order_id for update;
  if v_order_id is null then return; end if;
  update public.payments set status = 'failed' where order_id = v_order_id and status <> 'captured';
  update public.orders set status = 'cancelled', cancelled_at = coalesce(cancelled_at, now()) where id = v_order_id and status in ('placed','accepted');
  perform public.restore_order_stock(v_order_id);
end;
$$;
grant execute on function public.restore_order_stock(bigint) to service_role;
grant execute on function public.system_mark_payment_failed(text) to service_role;

create or replace function public.customer_mark_payment_captured(p_order_id bigint, p_gateway_order_id text, p_gateway_payment_id text, p_gateway_signature text)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  update public.payments p set status = 'captured', gateway_order_id = p_gateway_order_id, gateway_payment_id = p_gateway_payment_id, gateway_signature = p_gateway_signature, captured_at = coalesce(captured_at, now())
  from public.orders o where p.order_id = p_order_id and o.id = p.order_id and o.user_id = auth.uid() and (p.status = 'pending' or p.status = 'captured');
  if not found then raise exception 'PAYMENT_NOT_FOUND'; end if;
  update public.orders set payment_captured_at = coalesce(payment_captured_at, now()) where id = p_order_id and user_id = auth.uid();
  return true;
end;
$$;
grant execute on function public.customer_mark_payment_captured(bigint,text,text,text) to authenticated;

create or replace function public.system_process_payment_event(p_event_id text, p_event_name text, p_gateway_order_id text, p_gateway_payment_id text, p_payload jsonb)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_order_id bigint; v_inserted integer;
begin
  insert into public.payment_events(event_id, event_name, gateway_order_id, gateway_payment_id, payload) values (p_event_id, p_event_name, p_gateway_order_id, p_gateway_payment_id, coalesce(p_payload, '{}'::jsonb)) on conflict (provider, event_id) do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then return true; end if;
  select order_id into v_order_id from public.payments where gateway_order_id = p_gateway_order_id for update;
  if p_event_name = 'payment.captured' then
    update public.payments set status = 'captured', gateway_payment_id = coalesce(p_gateway_payment_id, gateway_payment_id), captured_at = coalesce(captured_at, now()) where gateway_order_id = p_gateway_order_id;
    update public.orders set payment_captured_at = coalesce(payment_captured_at, now()) where id = v_order_id;
  elsif p_event_name = 'payment.failed' then
    perform public.system_mark_payment_failed(p_gateway_order_id);
  end if;
  return true;
end;
$$;
grant execute on function public.system_process_payment_event(text,text,text,text,jsonb) to service_role;

create or replace function public.admin_update_order_status(p_order_id bigint, p_status public.order_status)
returns public.order_status language plpgsql security definer set search_path = public as $$
declare v_old public.order_status; v_new public.order_status;
begin
  if not public.has_role('store_manager') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  select status into v_old from public.orders where id = p_order_id for update;
  if v_old is null then raise exception 'ORDER_NOT_FOUND'; end if;
  if not ((v_old = 'placed' and p_status in ('accepted','cancelled')) or (v_old = 'accepted' and p_status in ('picking','cancelled')) or (v_old = 'picking' and p_status = 'packed') or (v_old = 'packed' and p_status = 'out_for_delivery') or (v_old = 'out_for_delivery' and p_status = 'delivered') or (v_old = 'delivered' and p_status = 'returned') or (p_status = 'refunded' and v_old in ('cancelled','returned'))) then raise exception 'INVALID_STATUS_TRANSITION'; end if;
  update public.orders set status = p_status, cancelled_at = case when p_status = 'cancelled' then coalesce(cancelled_at, now()) else cancelled_at end where id = p_order_id returning status into v_new;
  if p_status in ('cancelled','returned','refunded') then perform public.restore_order_stock(p_order_id); end if;
  insert into public.audit_logs(actor_id, action, table_name, row_id, payload) values (auth.uid(), 'order_status_updated', 'orders', p_order_id::text, jsonb_build_object('from', v_old::text, 'to', p_status::text));
  return v_new;
end;
$$;
grant execute on function public.admin_update_order_status(bigint, public.order_status) to authenticated;
