-- Segment 6 picker and delivery operations.
-- Run after phase2_operations.sql and phase4_completion.sql.

alter table public.products add column if not exists shelf_number text;
alter table public.orders add column if not exists picker_id uuid references public.users(id);
alter table public.orders add column if not exists delivery_staff_id uuid references public.users(id);
alter table public.orders add column if not exists cod_collected_at timestamptz;
alter table public.orders add column if not exists cod_collected_amount numeric(12,2);
alter table public.order_items add column if not exists picked_quantity integer not null default 0;
alter table public.order_items add column if not exists picked_at timestamptz;
alter table public.order_items add column if not exists packed_at timestamptz;
alter table public.order_items add column if not exists barcode_verified boolean not null default false;
alter table public.order_items add column if not exists substitute_product_id bigint references public.products(id);

create table if not exists public.delivery_attempts (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  delivery_staff_id uuid references public.users(id),
  outcome text not null check (outcome in ('assigned','started','delivered','failed','rescheduled')),
  reason text,
  proof_url text,
  latitude numeric,
  longitude numeric,
  created_at timestamptz not null default now()
);
create index if not exists delivery_attempts_order_idx on public.delivery_attempts(order_id, created_at desc);
alter table public.delivery_attempts enable row level security;
drop policy if exists "staff read delivery attempts" on public.delivery_attempts;
create policy "staff read delivery attempts" on public.delivery_attempts for select using (public.has_role('delivery_boy') or public.has_role('store_manager') or exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));

create or replace function public.admin_assign_fulfilment(p_order_id bigint, p_picker_id uuid default null, p_delivery_staff_id uuid default null)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.has_role('store_manager') and not public.has_role('super_admin') then raise exception 'MANAGER_ROLE_REQUIRED'; end if;
  update public.orders set picker_id = coalesce(p_picker_id, picker_id), delivery_staff_id = coalesce(p_delivery_staff_id, delivery_staff_id), assigned_to = coalesce(p_delivery_staff_id, assigned_to) where id = p_order_id;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  insert into public.audit_logs(actor_id, action, table_name, row_id, payload) values (auth.uid(), 'fulfilment_assigned', 'orders', p_order_id::text, jsonb_build_object('picker_id', p_picker_id, 'delivery_staff_id', p_delivery_staff_id));
end;
$$;
grant execute on function public.admin_assign_fulfilment(bigint,uuid,uuid) to authenticated;

create or replace function public.admin_list_pick_items(p_order_id bigint)
returns table(order_item_id bigint, product_id bigint, product_name text, sku text, barcode text, shelf_number text, ordered_quantity integer, picked_quantity integer, barcode_verified boolean, status text)
language plpgsql security definer set search_path = public as $$
begin
  if not (public.has_role('picker') or public.has_role('store_manager') or public.has_role('super_admin')) then raise exception 'PICKER_ROLE_REQUIRED'; end if;
  return query select oi.id, p.id, p.name, p.sku, p.barcode, p.shelf_number, oi.quantity, oi.picked_quantity, oi.barcode_verified, case when oi.packed_at is not null then 'packed' when oi.picked_at is not null then 'picked' else 'pending' end
  from public.order_items oi join public.products p on p.id = oi.product_id where oi.order_id = p_order_id order by p.shelf_number nulls last, p.name;
end;
$$;
grant execute on function public.admin_list_pick_items(bigint) to authenticated;

create or replace function public.admin_mark_item_picked(p_order_item_id bigint, p_picked_quantity integer, p_barcode_verified boolean default false)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_order_id bigint;
begin
  if not (public.has_role('picker') or public.has_role('store_manager') or public.has_role('super_admin')) then raise exception 'PICKER_ROLE_REQUIRED'; end if;
  if p_picked_quantity < 0 then raise exception 'INVALID_QUANTITY'; end if;
  update public.order_items set picked_quantity = p_picked_quantity, picked_at = case when p_picked_quantity > 0 then coalesce(picked_at, now()) else null end, barcode_verified = p_barcode_verified where id = p_order_item_id returning order_id into v_order_id;
  if v_order_id is null then raise exception 'ORDER_ITEM_NOT_FOUND'; end if;
  if not exists (select 1 from public.order_items where order_id = v_order_id and picked_quantity < quantity) then update public.orders set status = 'packed' where id = v_order_id and status in ('accepted','picking'); end if;
  return true;
end;
$$;
grant execute on function public.admin_mark_item_picked(bigint,integer,boolean) to authenticated;

create or replace function public.admin_record_delivery_attempt(p_order_id bigint, p_outcome text, p_reason text default null, p_proof_url text default null, p_latitude numeric default null, p_longitude numeric default null, p_cod_amount numeric default null)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not (public.has_role('delivery_boy') or public.has_role('store_manager') or public.has_role('super_admin')) then raise exception 'DELIVERY_ROLE_REQUIRED'; end if;
  insert into public.delivery_attempts(order_id, delivery_staff_id, outcome, reason, proof_url, latitude, longitude) values (p_order_id, auth.uid(), p_outcome, p_reason, p_proof_url, p_latitude, p_longitude);
  if p_outcome = 'delivered' then update public.orders set status = 'delivered', proof_of_delivery_url = coalesce(p_proof_url, proof_of_delivery_url), cod_collected_at = case when p_cod_amount is not null then now() else cod_collected_at end, cod_collected_amount = coalesce(p_cod_amount, cod_collected_amount) where id = p_order_id;
  elsif p_outcome = 'failed' then update public.orders set status = 'returned', delivery_notes = concat_ws(' · ', delivery_notes, coalesce(p_reason, 'Delivery failed')) where id = p_order_id;
  elsif p_outcome = 'started' then update public.orders set status = 'out_for_delivery' where id = p_order_id and status = 'packed';
  end if;
end;
$$;
grant execute on function public.admin_record_delivery_attempt(bigint,text,text,text,numeric,numeric,numeric) to authenticated;
