-- Segment 3 customer shopping experience.
-- Run after the existing customer, checkout, and completion migrations.

alter table public.orders add column if not exists contactless_delivery boolean not null default false;
alter table public.orders add column if not exists substitute_unavailable boolean not null default false;
alter table public.orders add column if not exists guest_email text;
alter table public.orders add column if not exists guest_phone text;

create table if not exists public.gift_vouchers (
  id bigint generated by default as identity primary key,
  code text unique not null,
  initial_balance numeric(12,2) not null check (initial_balance >= 0),
  remaining_balance numeric(12,2) not null check (remaining_balance >= 0 and remaining_balance <= initial_balance),
  expires_at timestamptz,
  owner_id uuid references public.users(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.recently_viewed (
  user_id uuid not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key(user_id, product_id)
);

alter table public.gift_vouchers enable row level security;
alter table public.recently_viewed enable row level security;
drop policy if exists "customers read own vouchers" on public.gift_vouchers;
create policy "customers read own vouchers" on public.gift_vouchers for select using (owner_id = auth.uid());
drop policy if exists "customers manage own recently viewed" on public.recently_viewed;
create policy "customers manage own recently viewed" on public.recently_viewed for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create index if not exists recently_viewed_user_idx on public.recently_viewed(user_id, viewed_at desc);
create index if not exists gift_vouchers_owner_idx on public.gift_vouchers(owner_id, active, expires_at);

create or replace function public.customer_save_recently_viewed(p_product_id bigint)
returns void language plpgsql security invoker set search_path = public as $$
begin
  if auth.uid() is null or not exists (select 1 from public.products where id = p_product_id and is_active) then return; end if;
  insert into public.recently_viewed(user_id, product_id, viewed_at) values (auth.uid(), p_product_id, now())
  on conflict (user_id, product_id) do update set viewed_at = excluded.viewed_at;
  delete from public.recently_viewed where user_id = auth.uid() and product_id in (select product_id from public.recently_viewed where user_id = auth.uid() order by viewed_at desc offset 20);
end;
$$;
grant execute on function public.customer_save_recently_viewed(bigint) to authenticated;

create or replace function public.customer_wallet_balance()
returns numeric language sql security invoker set search_path = public as $$
  select coalesce(sum(amount), 0) from public.wallet_transactions where user_id = auth.uid();
$$;
grant execute on function public.customer_wallet_balance() to authenticated;

create or replace function public.customer_reward_balance()
returns integer language sql security invoker set search_path = public as $$
  select coalesce((select balance from public.reward_points where user_id = auth.uid()), 0);
$$;
grant execute on function public.customer_reward_balance() to authenticated;

create or replace function public.customer_validate_voucher(p_code text)
returns table(valid boolean, balance numeric, message text)
language sql security invoker set search_path = public as $$
  select true, remaining_balance, 'Gift voucher applied.' from public.gift_vouchers
  where owner_id = auth.uid() and upper(code) = upper(trim(p_code)) and active and remaining_balance > 0 and (expires_at is null or expires_at >= now())
  limit 1;
$$;
grant execute on function public.customer_validate_voucher(text) to authenticated;

-- Home-page merchandising sections use stable views, so the UI does not hard-code product IDs.
create or replace view public.customer_best_sellers as
select p.id, p.name, sum(oi.quantity)::integer as units_sold
from public.products p join public.order_items oi on oi.product_id = p.id join public.orders o on o.id = oi.order_id
where p.is_active and o.status not in ('cancelled','refunded')
group by p.id, p.name order by units_sold desc limit 12;
create or replace view public.customer_new_arrivals as
select id, name, created_at from public.products where is_active order by created_at desc limit 12;
alter view public.customer_best_sellers set (security_invoker = true);
alter view public.customer_new_arrivals set (security_invoker = true);
