-- Segment 5 inventory and product operations.
-- Run after the previous schema and payment/order migrations.

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  quantity integer not null,
  movement_type text not null check (movement_type in ('purchase','sale','reserve','release','return','wastage','damage','transfer_in','transfer_out','adjustment')),
  reference_type text,
  reference_id text,
  warehouse text not null default 'default',
  batch_number text,
  reason text,
  actor_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);
create index if not exists inventory_movements_product_idx on public.inventory_movements(product_id, created_at desc);
create index if not exists inventory_movements_reference_idx on public.inventory_movements(reference_type, reference_id);

create table if not exists public.inventory_reservations (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  status text not null default 'reserved' check (status in ('reserved','committed','released')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create unique index if not exists inventory_reservation_active_idx on public.inventory_reservations(order_id, product_id) where status = 'reserved';
create index if not exists inventory_reservation_order_idx on public.inventory_reservations(order_id, status);

create table if not exists public.low_stock_alerts (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  current_stock integer not null,
  reorder_level integer not null,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists low_stock_open_alert_idx on public.low_stock_alerts(product_id) where acknowledged_at is null;

create table if not exists public.purchase_receipts (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders(id),
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  batch_number text,
  expiry_date date,
  received_by uuid references auth.users(id),
  received_at timestamptz not null default now()
);

alter table public.inventory_movements enable row level security;
alter table public.inventory_reservations enable row level security;
alter table public.low_stock_alerts enable row level security;
alter table public.purchase_receipts enable row level security;
drop policy if exists "staff read inventory movements" on public.inventory_movements;
create policy "staff read inventory movements" on public.inventory_movements for select using (public.has_role('inventory_manager') or public.has_role('store_manager') or public.has_role('accountant'));
drop policy if exists "staff read reservations" on public.inventory_reservations;
create policy "staff read reservations" on public.inventory_reservations for select using (public.has_role('inventory_manager') or public.has_role('store_manager'));
drop policy if exists "staff read low stock alerts" on public.low_stock_alerts;
create policy "staff read low stock alerts" on public.low_stock_alerts for select using (public.has_role('inventory_manager') or public.has_role('store_manager'));
drop policy if exists "staff read purchase receipts" on public.purchase_receipts;
create policy "staff read purchase receipts" on public.purchase_receipts for select using (public.has_role('inventory_manager') or public.has_role('store_manager'));

create or replace function public.create_low_stock_alert()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.current_stock <= new.reorder_level then
    insert into public.low_stock_alerts(product_id, current_stock, reorder_level) values (new.product_id, new.current_stock, new.reorder_level) on conflict (product_id) where acknowledged_at is null do update set current_stock = excluded.current_stock, reorder_level = excluded.reorder_level;
  else
    update public.low_stock_alerts set acknowledged_at = coalesce(acknowledged_at, now()) where product_id = new.product_id and acknowledged_at is null;
  end if;
  return new;
end;
$$;
drop trigger if exists inventory_low_stock_alert on public.inventory;
create trigger inventory_low_stock_alert after insert or update of current_stock, reorder_level on public.inventory for each row execute function public.create_low_stock_alert();

create or replace function public.reserve_inventory(p_order_id bigint, p_product_id bigint, p_quantity integer)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'INVALID_QUANTITY'; end if;
  update public.inventory set reserved_stock = reserved_stock + p_quantity where product_id = p_product_id and current_stock - reserved_stock >= p_quantity;
  if not found then raise exception 'INSUFFICIENT_STOCK'; end if;
  insert into public.inventory_reservations(order_id, product_id, quantity) values (p_order_id, p_product_id, p_quantity) on conflict (order_id, product_id) where status = 'reserved' do update set quantity = inventory_reservations.quantity + excluded.quantity;
  insert into public.inventory_movements(product_id, quantity, movement_type, reference_type, reference_id, actor_id) values (p_product_id, p_quantity, 'reserve', 'order', p_order_id::text, auth.uid());
  return true;
end;
$$;

create or replace function public.release_inventory_reservation(p_order_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.inventory i set reserved_stock = greatest(0, i.reserved_stock - r.quantity) from public.inventory_reservations r where r.order_id = p_order_id and r.status = 'reserved' and r.product_id = i.product_id;
  insert into public.inventory_movements(product_id, quantity, movement_type, reference_type, reference_id, actor_id) select product_id, quantity, 'release', 'order', p_order_id::text, auth.uid() from public.inventory_reservations where order_id = p_order_id and status = 'reserved';
  update public.inventory_reservations set status = 'released', resolved_at = now() where order_id = p_order_id and status = 'reserved';
end;
$$;

create or replace function public.commit_inventory_reservation(p_order_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.inventory i set current_stock = i.current_stock - r.quantity, reserved_stock = greatest(0, i.reserved_stock - r.quantity) from public.inventory_reservations r where r.order_id = p_order_id and r.status = 'reserved' and r.product_id = i.product_id;
  insert into public.inventory_movements(product_id, quantity, movement_type, reference_type, reference_id, actor_id) select product_id, quantity, 'sale', 'order', p_order_id::text, auth.uid() from public.inventory_reservations where order_id = p_order_id and status = 'reserved';
  update public.inventory_reservations set status = 'committed', resolved_at = now() where order_id = p_order_id and status = 'reserved';
end;
$$;
grant execute on function public.reserve_inventory(bigint,bigint,integer) to authenticated;
grant execute on function public.release_inventory_reservation(bigint) to service_role;
grant execute on function public.commit_inventory_reservation(bigint) to service_role;

create or replace function public.admin_receive_purchase(p_purchase_order_id bigint, p_product_id bigint, p_quantity integer, p_batch_number text default null, p_expiry_date date default null)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if not (public.has_role('inventory_manager') or public.has_role('store_manager')) then raise exception 'INVENTORY_ROLE_REQUIRED'; end if;
  if p_quantity <= 0 then raise exception 'INVALID_QUANTITY'; end if;
  insert into public.purchase_receipts(purchase_order_id, product_id, quantity, batch_number, expiry_date, received_by) values (p_purchase_order_id, p_product_id, p_quantity, p_batch_number, p_expiry_date, auth.uid());
  insert into public.inventory_batches(product_id, batch_number, expiry_date, quantity) values (p_product_id, coalesce(p_batch_number, 'UNBATCHED'), p_expiry_date, p_quantity);
  insert into public.inventory(product_id, current_stock, warehouse_stock) values (p_product_id, p_quantity, p_quantity) on conflict (product_id) do update set current_stock = inventory.current_stock + excluded.current_stock, warehouse_stock = inventory.warehouse_stock + excluded.warehouse_stock;
  insert into public.inventory_movements(product_id, quantity, movement_type, reference_type, reference_id, batch_number, actor_id) values (p_product_id, p_quantity, 'purchase', 'purchase_order', p_purchase_order_id::text, p_batch_number, auth.uid());
  return true;
end;
$$;
grant execute on function public.admin_receive_purchase(bigint,bigint,integer,text,date) to authenticated;

create or replace function public.admin_adjust_inventory_with_batch(
  p_product_id bigint,
  p_delta integer,
  p_reason text default 'Stock correction',
  p_batch_number text default null,
  p_expiry_date date default null
)
returns integer language plpgsql security definer set search_path = public as $$
declare v_stock integer;
begin
  if not (public.has_role('inventory_manager') or public.has_role('store_manager')) then raise exception 'INVENTORY_ROLE_REQUIRED'; end if;
  if p_delta = 0 then raise exception 'INVALID_DELTA'; end if;
  update public.inventory
  set current_stock = current_stock + p_delta,
      warehouse_stock = warehouse_stock + p_delta
  where product_id = p_product_id and current_stock + p_delta >= reserved_stock
  returning current_stock into v_stock;
  if v_stock is null then raise exception 'INVENTORY_NOT_FOUND_OR_BELOW_RESERVED'; end if;
  if p_delta > 0 then
    insert into public.inventory_batches(product_id, batch_number, expiry_date, quantity)
    values (p_product_id, coalesce(nullif(trim(p_batch_number), ''), 'UNBATCHED'), p_expiry_date, p_delta);
  end if;
  insert into public.inventory_movements(product_id, quantity, movement_type, reference_type, reference_id, batch_number, reason, actor_id)
  values (p_product_id, abs(p_delta), case when p_delta > 0 then 'adjustment' else 'wastage' end, 'manual_adjustment', p_product_id::text, p_batch_number, p_reason, auth.uid());
  return v_stock;
end;
$$;
grant execute on function public.admin_adjust_inventory_with_batch(bigint,integer,text,text,date) to authenticated;
