'use client'

import { useEffect, useState } from 'react'
import { AdminShell } from '../admin-shell'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'
import { money } from '@/lib/formatters'
import { useRealtimeReload } from '@/lib/use-realtime-reload'
import type { AdminCoupon } from '@/types/admin'

export function LiveCouponManager() {
  const [coupons, setCoupons] = useState<AdminCoupon[]>([]); const [form, setForm] = useState({ code: '', kind: 'percentage', value: '10', active: true }); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  async function load() { const client = createSupabaseBrowserClient(); if (!client) return; const { data, error: queryError } = await client.rpc('admin_list_coupons'); if (queryError) { setError(queryError.message); setMessage('') } else { setCoupons((data ?? []) as AdminCoupon[]); setError('') } }
  useEffect(() => { void load() }, [])
  useRealtimeReload('admin-coupons-live', ['coupons'], () => { void load() })
  async function save() { setError(''); setMessage(''); const client = createSupabaseBrowserClient(); if (!client) return; const { error: saveError } = await client.rpc('admin_upsert_coupon', { p_code: form.code, p_kind: form.kind, p_value: Number(form.value), p_active: form.active }); if (saveError) setError(saveError.message); else { setMessage('Coupon saved.'); setForm({ code: '', kind: 'percentage', value: '10', active: true }); await load() } }
  async function remove(coupon: AdminCoupon) { if (!window.confirm(`Delete coupon ${coupon.code}?`)) return; setError(''); setMessage(''); const client = createSupabaseBrowserClient(); if (!client) return; const { error: deleteError } = await client.rpc('admin_delete_coupon', { p_coupon_id: coupon.coupon_id }); if (deleteError) setError(deleteError.message); else { setMessage(`Coupon ${coupon.code} deleted.`); await load() } }
  return <AdminShell title="Coupon engine" description="Create and manage live discount rules stored in Supabase."><div className="management-layout"><section className="panel form-panel"><h2>New coupon</h2><div className="form-grid"><label>Code<input value={form.code} onChange={event => setForm({ ...form, code: event.target.value })} placeholder="CARTLY10" /></label><label>Type<select value={form.kind} onChange={event => setForm({ ...form, kind: event.target.value })}><option value="percentage">Percentage</option><option value="flat">Flat amount</option><option value="free_delivery">Free delivery</option></select></label><label>Value<input type="number" value={form.value} onChange={event => setForm({ ...form, value: event.target.value })} /></label></div><label className="checkbox-line"><input type="checkbox" checked={form.active} onChange={event => setForm({ ...form, active: event.target.checked })} /> Active</label><button className="primary-button" onClick={() => void save()}>Save coupon</button>{error && <p className="low-stock">{error}</p>}{message && <p className="success-message">{message}</p>}</section><section className="panel table-panel"><div className="panel-heading"><h2>Live coupons</h2><button className="secondary-button" onClick={() => void load()}>Refresh</button></div><div className="inventory-table"><div className="table-head"><span>Code</span><span>Type</span><span>Value</span><span>Status</span><span>Actions</span></div>{coupons.map(coupon => <div className="table-row" key={coupon.coupon_id}><span><strong>{coupon.code}</strong></span><span>{coupon.kind}</span><span>{coupon.kind === 'percentage' ? `${coupon.value}%` : money(Number(coupon.value))}</span><span>{coupon.active ? 'Active' : 'Inactive'}</span><span><button className="link-button" onClick={() => void remove(coupon)} aria-label={`Delete ${coupon.code}`}>Delete</button></span></div>)}</div></section></div></AdminShell>
}
