'use client'

import { AnimatePresence, m } from 'framer-motion'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import { money } from '@/lib/formatters'
import { orderStatuses } from '@/constants/admin-orders'
import type { AdminOrder } from '@/types/admin-orders'

export function OrderQueueTable({ loading, visibleOrders, pageRows, page, totalPages, setPage, busy, updateStatus, query, status }: { loading: boolean; visibleOrders: AdminOrder[]; pageRows: AdminOrder[]; page: number; totalPages: number; setPage: (value: number | ((current: number) => number)) => void; busy: number | null; updateStatus: (orderId: number, nextStatus: string) => void; query: string; status: string }) {
  return <>{loading ? <div className="table-loading"><span /><span /><span /><span /><span /></div> : visibleOrders.length ? <><div className="inventory-table admin-data-table"><div className="table-head"><span>Order</span><span>Customer</span><span>Total</span><span>Address</span><span>Status</span></div><AnimatePresence mode="popLayout">{pageRows.map(order => <m.div className="table-row" key={order.order_id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .2 }}><span><strong>#{order.order_id}</strong><small>{new Date(order.created_at).toLocaleDateString('en-IN')}</small></span><span><strong>{order.customer_name}</strong><small>{order.customer_email}</small></span><span><strong>{money(Number(order.total))}</strong><small>{order.item_count} item{order.item_count === 1 ? '' : 's'}</small></span><span>{order.address_line || 'No address provided'}</span><span><select className="status-select" value={order.status} disabled={busy === order.order_id} onChange={event => void updateStatus(order.order_id, event.target.value)} aria-label={`Update order ${order.order_id} status`}>{orderStatuses.map(item => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select></span></m.div>)}</AnimatePresence></div><div className="table-pagination"><span>Page {page} of {totalPages}</span><div><button onClick={() => setPage(current => Math.max(1, current - 1))} disabled={page === 1} aria-label="Previous page"><ChevronLeft size={15} /></button><button onClick={() => setPage(current => Math.min(totalPages, current + 1))} disabled={page === totalPages} aria-label="Next page"><ChevronRight size={15} /></button></div></div></> : <section className="placeholder compact-empty"><h2>{query || status ? 'No matching orders' : 'No orders yet'}</h2><p>{query || status ? 'Try a different search or status filter.' : 'New customer orders will appear here.'}</p></section>}</>
}
