import Link from "next/link";
import { requireAdmin } from "@/lib/admin-auth-guard";
import { connectDB } from "@/lib/db";
import User from "@/models/User";
import { getBanLabel } from "@/lib/account-status";
import { adminPath } from "@/lib/admin-route";
import { banUserAction } from "./actions";

export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string; error?: string; success?: string }> }) {
  await requireAdmin(); const query = await searchParams; const q = String(query.q || "").trim(); const page = Math.max(1, Number(query.page || 1)); const limit = 25;
  const filter = q ? { $or: [{ name: { $regex: q, $options: "i" } }, { username: { $regex: q, $options: "i" } }, { email: { $regex: q, $options: "i" } }] } : {};
  await connectDB(); const [users, total] = await Promise.all([User.find(filter).select("name username email createdAt warningCount bannedUntil bannedPermanently").sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean<any[]>(), User.countDocuments(filter)]); const pages = Math.max(1, Math.ceil(total / limit));
  return (<><h1 className="admin-title">Users</h1><p className="admin-muted">Profile-level moderation context only. Messages are available only through individual flags.</p>{query.error && <div className="admin-alert">Unable to complete that user action.</div>}{query.success === "deleted" && <div className="admin-success">User and related data removed.</div>}<div className="admin-card"><form className="admin-form-inline" method="GET"><div className="admin-field" style={{ flex: 1 }}><label htmlFor="q">Search name, username, or email</label><input id="q" name="q" defaultValue={q} className="admin-input" /></div><button type="submit" className="admin-button">Search</button></form></div><div className="admin-card admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Email</th><th>Joined</th><th>Ban</th><th>Warnings</th><th>Actions</th></tr></thead><tbody>{users.map((user: any) => <tr key={user._id}><td><Link href={adminPath(`/users/${user._id}`)} style={{ color: "#7ee2b8", fontWeight: 700 }}>{user.name}</Link><div className="admin-muted">@{user.username}</div></td><td>{user.email}</td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td>{getBanLabel(user)}</td><td>{user.warningCount || 0}</td><td><div className="admin-user-actions"><Link href={adminPath(`/users/${user._id}`)} className="admin-button secondary">Manage</Link><form action={banUserAction}><input type="hidden" name="userId" value={String(user._id)} /><input type="hidden" name="mode" value="permanent" /><input type="hidden" name="reason" value="Permanent ban from user moderation list" /><button type="submit" className="admin-button danger">Ban</button></form></div></td></tr>)}{users.length === 0 && <tr><td colSpan={6} className="admin-muted">No users matched.</td></tr>}</tbody></table><div className="admin-pagination"><span className="admin-muted">Page {page} of {pages}</span><div className="admin-actions">{page > 1 && <Link className="admin-button secondary" href={`${adminPath("/users")}?q=${encodeURIComponent(q)}&page=${page - 1}`}>Previous</Link>}{page < pages && <Link className="admin-button secondary" href={`${adminPath("/users")}?q=${encodeURIComponent(q)}&page=${page + 1}`}>Next</Link>}</div></div></div></>);
}
