'use client'

import { useEffect, useState } from 'react'
import { AdminShell } from './admin-shell'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'
import { useRealtimeReload } from '@/lib/use-realtime-reload'

type Banner = { banner_id: number; placement: string; title: string; copy: string | null; image_url: string; active: boolean; sort_order: number }
const blank = { placement: 'homepage', title: '', copy: '', imageUrl: '', sortOrder: '0', active: true }

export function BannerManager() {
  const [banners, setBanners] = useState<Banner[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<number | null>(null); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  async function load() { const client = createSupabaseBrowserClient(); if (!client) return; const { data, error: queryError } = await client.rpc('admin_list_banners'); if (queryError) setError(queryError.message); else setBanners((data ?? []) as Banner[]) }
  useEffect(() => { void load() }, [])
  useRealtimeReload('admin-banners-live', ['banners'], () => { void load() })
  async function save() { setError(''); setMessage(''); const client = createSupabaseBrowserClient(); if (!client) return; const { error: saveError } = await client.rpc('admin_upsert_banner', { p_banner_id: editing, p_placement: form.placement, p_title: form.title, p_copy: form.copy || null, p_image_url: form.imageUrl, p_active: form.active, p_sort_order: Number(form.sortOrder) }); if (saveError) setError(saveError.message); else { setMessage('Banner saved.'); setEditing(null); setForm(blank); await load() } }
  function edit(banner: Banner) { setEditing(banner.banner_id); setForm({ placement: banner.placement, title: banner.title, copy: banner.copy ?? '', imageUrl: banner.image_url, sortOrder: String(banner.sort_order), active: banner.active }) }
  return <AdminShell title="Banner management" description="Manage live homepage and category promotional placements."><div className="management-layout"><section className="panel form-panel"><h2>{editing ? 'Edit banner' : 'New banner'}</h2><div className="form-grid"><label>Placement<input value={form.placement} onChange={event => setForm({ ...form, placement: event.target.value })} placeholder="homepage or groceries" /></label><label>Title<input value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></label><label>Image URL<input value={form.imageUrl} onChange={event => setForm({ ...form, imageUrl: event.target.value })} /></label><label>Sort order<input type="number" value={form.sortOrder} onChange={event => setForm({ ...form, sortOrder: event.target.value })} /></label><label>Copy<textarea value={form.copy} onChange={event => setForm({ ...form, copy: event.target.value })} /></label></div><label className="checkbox-line"><input type="checkbox" checked={form.active} onChange={event => setForm({ ...form, active: event.target.checked })} /> Active</label><button className="primary-button" onClick={() => void save()}>Save banner</button>{editing && <button className="secondary-button" onClick={() => { setEditing(null); setForm(blank) }}>Cancel edit</button>}{error && <p className="low-stock">{error}</p>}{message && <p className="success-message">{message}</p>}</section><section className="panel table-panel"><div className="panel-heading"><h2>Live banners</h2><button className="secondary-button" onClick={() => void load()}>Refresh</button></div><div className="inventory-table"><div className="table-head"><span>Preview</span><span>Placement</span><span>Title</span><span>Status</span><span>Action</span></div>{banners.map(banner => <div className="table-row" key={banner.banner_id}><span><img src={banner.image_url} alt="" width="64" height="36" /></span><span>{banner.placement}</span><span>{banner.title}</span><span>{banner.active ? 'Active' : 'Inactive'}</span><span><button className="link-button" onClick={() => edit(banner)}>Edit</button></span></div>)}</div></section></div></AdminShell>
}
