'use client'

import { useEffect, useState } from 'react'
import { AdminShell } from './admin-shell'
import { emptyProductForm, type CouponRule, type InventoryAdjustment, type ProductForm, type SupportTicket } from '@/lib/services/admin'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'
import { useRealtimeReload } from '@/lib/use-realtime-reload'

export function ProductManager() {
  const [form, setForm] = useState<ProductForm>(emptyProductForm)
  const [saved, setSaved] = useState(false)
  const update = (key: keyof ProductForm, value: string) => setForm(current => ({ ...current, [key]: value }))
  return <AdminShell title="Product management" description="CRUD, media, variants, catalogue metadata and bulk upload controls."><div className="management-layout"><section className="panel form-panel"><h2>Add or edit product</h2><p>Create simple, variable, loose-weight, combo, subscription and gift products.</p><div className="form-grid product-form">{[['name', 'Product name'], ['sku', 'SKU'], ['barcode', 'Barcode'], ['brand', 'Brand'], ['category', 'Category'], ['price', 'Selling price'], ['gst', 'GST %'], ['hsn', 'HSN code'], ['stock', 'Current stock'], ['seoTitle', 'SEO title']].map(([key, label]) => <label key={key}>{label}<input value={form[key as keyof ProductForm]} onChange={event => update(key as keyof ProductForm, event.target.value)} /></label>)}<label>Description<textarea value={form.description} onChange={event => update('description', event.target.value)} /></label><label>SEO description<textarea value={form.seoDescription} onChange={event => update('seoDescription', event.target.value)} /></label></div><div className="upload-zone">Drop multiple images or product video here<br /><small>Bulk images, JPG/PNG/WebP and MP4 ready for Supabase Storage</small></div><div className="form-actions"><button className="secondary-button" onClick={() => setForm(emptyProductForm)}>Clear</button><button className="primary-button" onClick={() => setSaved(true)}>Save product</button></div>{saved && <p className="success-message">✓ Product draft saved locally. Supabase insert will connect here.</p>}</section><section className="panel"><h2>Bulk catalogue tools</h2><p>Import product data and media without editing each item manually.</p><div className="feature-card compact"><b>⇧</b><h3>CSV / Excel upload</h3><p>Upload products, variants, SKU, barcode, GST, HSN and SEO fields.</p><button className="secondary-button">Choose file</button></div><div className="feature-card compact"><b>▧</b><h3>Bulk image upload</h3><p>Match images by SKU and prepare signed Supabase Storage URLs.</p><button className="secondary-button">Choose images</button></div><div className="feature-card compact"><b>◇</b><h3>Related products</h3><p>Connect similar products, frequently bought together and brand relationships.</p><button className="secondary-button">Configure</button></div></section></div></AdminShell>
}

export function InventoryManager() {
  const [adjustment, setAdjustment] = useState<InventoryAdjustment>({ product: 'Soundcore Life Q30', warehouse: 'Mumbai Central', quantity: '', reason: 'Stock correction', batch: '', expiry: '' })
  const [items, setItems] = useState<Array<{ product_id: number; product_name: string; sku: string | null; current_stock: number; reserved_stock: number; reorder_level: number }>>([])
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  async function load() {
    const client = createSupabaseBrowserClient()
    if (!client) return
    const { data, error: queryError } = await client.rpc('admin_list_inventory')
    if (queryError) setError(queryError.message)
    else setItems((data ?? []) as typeof items)
  }
  useEffect(() => { void load() }, [])
  useRealtimeReload('admin-inventory-live', ['inventory', 'products'], () => { void load() })
  async function saveAdjustment() {
    setError(''); setMessage('')
    const item = items.find(entry => entry.product_name === adjustment.product)
    const delta = Number(adjustment.quantity)
    if (!item || !Number.isInteger(delta) || delta === 0) { setError('Choose a product and enter a non-zero whole-number adjustment.'); return }
    const client = createSupabaseBrowserClient()
    if (!client) return
    const { error: updateError } = await client.rpc('admin_adjust_inventory_with_batch', { p_product_id: item.product_id, p_delta: delta, p_reason: adjustment.reason, p_batch_number: adjustment.batch || null, p_expiry_date: adjustment.expiry || null })
    if (updateError) setError(updateError.message)
    else { setMessage('Inventory updated in Supabase.'); setAdjustment(current => ({ ...current, quantity: '' })); await load() }
  }
  return <AdminShell title="Inventory controls" description="Adjust stock, manage batches, warehouses, expiry dates, suppliers and purchase history."><div className="management-layout"><section className="panel form-panel"><h2>Stock adjustment</h2><p>Current stock is read from Supabase and adjustments are audited.</p><div className="form-grid"><label>Product<select value={adjustment.product} onChange={event => setAdjustment({ ...adjustment, product: event.target.value })}>{items.map(item => <option key={item.product_id}>{item.product_name}</option>)}</select></label><label>Warehouse<select value={adjustment.warehouse} onChange={event => setAdjustment({ ...adjustment, warehouse: event.target.value })}><option>Mumbai Central</option><option>Bengaluru South</option><option>Delhi NCR</option></select></label><label>Quantity<input value={adjustment.quantity} onChange={event => setAdjustment({ ...adjustment, quantity: event.target.value })} placeholder="+20 or -5" /></label><label>Reason<select value={adjustment.reason} onChange={event => setAdjustment({ ...adjustment, reason: event.target.value })}><option>Stock correction</option><option>Wastage</option><option>Damaged goods</option><option>Stock transfer</option></select></label><label>Batch number<input value={adjustment.batch} onChange={event => setAdjustment({ ...adjustment, batch: event.target.value })} /></label><label>Expiry date<input type="date" value={adjustment.expiry} onChange={event => setAdjustment({ ...adjustment, expiry: event.target.value })} /></label></div><button className="primary-button" onClick={() => void saveAdjustment()}>Save adjustment</button>{error && <p className="low-stock">{error}</p>}{message && <p className="success-message">{message}</p>}</section><section className="panel table-panel"><div className="panel-heading"><div><h2>Live inventory</h2><p>Available, reserved and reorder thresholds.</p></div><button className="secondary-button" onClick={() => void load()}>Refresh</button></div><div className="inventory-table"><div className="table-head"><span>Product</span><span>SKU</span><span>Available</span><span>Reserved</span><span>Reorder at</span></div>{items.map(item => <div className="table-row" key={item.product_id}><span><strong>{item.product_name}</strong></span><span>{item.sku ?? '—'}</span><span className={item.current_stock <= item.reorder_level ? 'low-stock' : ''}>{item.current_stock}</span><span>{item.reserved_stock}</span><span>{item.reorder_level}</span></div>)}</div></section></div></AdminShell>
}

export function CouponManager() {
  const [rule, setRule] = useState<CouponRule>({ name: 'Cartly10', type: 'Percentage discount', value: '10', scope: 'First order', starts: '', ends: '', active: true })
  return <AdminShell title="Coupon engine" description="Percentage, flat, buy X get Y, free delivery, first order, category, brand and time-based rules."><section className="panel form-panel"><h2>Coupon rule builder</h2><div className="form-grid"><label>Coupon name<input value={rule.name} onChange={event => setRule({ ...rule, name: event.target.value })} /></label><label>Discount type<select value={rule.type} onChange={event => setRule({ ...rule, type: event.target.value })}><option>Percentage discount</option><option>Flat discount</option><option>Buy X get Y</option><option>Free delivery</option></select></label><label>Value<input value={rule.value} onChange={event => setRule({ ...rule, value: event.target.value })} /></label><label>Scope<select value={rule.scope} onChange={event => setRule({ ...rule, scope: event.target.value })}><option>First order</option><option>All customers</option><option>Category</option><option>Brand</option></select></label><label>Starts<input type="datetime-local" value={rule.starts} onChange={event => setRule({ ...rule, starts: event.target.value })} /></label><label>Ends<input type="datetime-local" value={rule.ends} onChange={event => setRule({ ...rule, ends: event.target.value })} /></label></div><label className="checkbox-line"><input type="checkbox" checked={rule.active} onChange={event => setRule({ ...rule, active: event.target.checked })} /> Active coupon</label><button className="primary-button">Save coupon rule</button></section></AdminShell>
}

export function SupportManager() {
  const [tickets, setTickets] = useState<SupportTicket[]>([{ id: 'ST-104', customer: 'Priya Sharma', subject: 'Missing item from order', priority: 'High', status: 'Open' }, { id: 'ST-103', customer: 'Rohan Mehta', subject: 'Refund status', priority: 'Medium', status: 'Assigned' }, { id: 'ST-102', customer: 'Meera Iyer', subject: 'Change delivery slot', priority: 'Low', status: 'Resolved' }])
  return <AdminShell title="Support tickets" description="Customer support tickets, refunds, replacements and service follow-up."><section className="panel table-panel"><div className="panel-heading"><div><h2>Ticket queue</h2><p>Manage customer conversations and connect them to orders.</p></div><button className="primary-button">+ New ticket</button></div><div className="inventory-table"><div className="table-head"><span>Ticket</span><span>Customer</span><span>Subject</span><span>Priority</span><span>Status</span></div>{tickets.map(ticket => <div className="table-row" key={ticket.id}><span><strong>{ticket.id}</strong></span><span>{ticket.customer}</span><span>{ticket.subject}</span><span>{ticket.priority}</span><span>{ticket.status}</span></div>)}</div><button className="secondary-button" onClick={() => setTickets(current => [...current, { id: 'ST-101', customer: 'Aarav Kapoor', subject: 'Replacement requested', priority: 'Medium', status: 'Open' }])}>Load more tickets</button></section></AdminShell>
}
