'use client'

import { useState } from 'react'
import { AdminShell } from '../admin-shell'
import { emptyProductForm, type ProductForm } from '@/lib/services/admin'

export function ProductManager() {
  const [form, setForm] = useState<ProductForm>(emptyProductForm)
  const [saved, setSaved] = useState(false)
  const update = (key: keyof ProductForm, value: string) => setForm(current => ({ ...current, [key]: value }))
  return <AdminShell title="Product management" description="CRUD, media, variants, catalogue metadata and bulk upload controls."><div className="management-layout"><section className="panel form-panel"><h2>Add or edit product</h2><p>Create simple, variable, loose-weight, combo, subscription and gift products.</p><div className="form-grid product-form">{[['name', 'Product name'], ['sku', 'SKU'], ['barcode', 'Barcode'], ['brand', 'Brand'], ['category', 'Category'], ['price', 'Selling price'], ['gst', 'GST %'], ['hsn', 'HSN code'], ['stock', 'Current stock'], ['seoTitle', 'SEO title']].map(([key, label]) => <label key={key}>{label}<input value={form[key as keyof ProductForm]} onChange={event => update(key as keyof ProductForm, event.target.value)} /></label>)}<label>Description<textarea value={form.description} onChange={event => update('description', event.target.value)} /></label><label>SEO description<textarea value={form.seoDescription} onChange={event => update('seoDescription', event.target.value)} /></label></div><div className="upload-zone">Drop multiple images or product video here<br /><small>Bulk images, JPG/PNG/WebP and MP4 ready for Supabase Storage</small></div><div className="form-actions"><button className="secondary-button" onClick={() => setForm(emptyProductForm)}>Clear</button><button className="primary-button" onClick={() => setSaved(true)}>Save product</button></div>{saved && <p className="success-message">Product draft saved locally. Supabase insert will connect here.</p>}</section><section className="panel"><h2>Bulk catalogue tools</h2><p>Import product data and media without editing each item manually.</p><div className="feature-card compact"><b>⇧</b><h3>CSV / Excel upload</h3><p>Upload products, variants, SKU, barcode, GST, HSN and SEO fields.</p><button className="secondary-button">Choose file</button></div><div className="feature-card compact"><b>▧</b><h3>Bulk image upload</h3><p>Match images by SKU and prepare signed Supabase Storage URLs.</p><button className="secondary-button">Choose images</button></div><div className="feature-card compact"><b>◇</b><h3>Related products</h3><p>Connect similar products, frequently bought together and brand relationships.</p><button className="secondary-button">Configure</button></div></section></div></AdminShell>
}
